### ISSUE TITLE
Create and Review 1 KB Article (Each Agent)

### ISSUE THREAD

**Issue by samuelweblink** [hostinger/brazil#1]
After creating and reviewing, comment on this issue with ID of created and reviewed articles

- [x] Marcelo A.
- [x] Luiz O.
- [x] Victor M.
- [x] Patrick R.  
- [x] Sabrina N.
- [x] Jeive G.
- [x] Derek
- [x] José R.
- [x] Jonas C.
- [x] Ismael O.
- [x] Raphael S.
- [x] Leonardo P.
- [x] Jonathan A.
- [x] Lucas Q.
- [x] Lucas M.
- [x] Vinicius J.
- [x] Brendon M.
- [x] Fernando M.
- [x] Matheus V. 
- [x] Daniel M.
- [x] Sidnei P.
- [x] Raquel F.
- [x] Bruno S.
- [x] Ruan A.

**Comment by lucasquevedo** [comment]
Created: 1791952 (Note: Already published due to demand, please review this one)
Reviewed: 1818437 (Note: Added new images, description and text linebreaks)

**Comment by brendonmarques** [comment]
Created: work in progress
Reviewed: 1820901 (updated images and small gramatical errors)

**Comment by danielmoretto** [comment]
Created: 1837275
Reviewed: 1808742 ( Revamped adding tutorial with images on how to download, install and connect the application)

**Comment by lucasmartins94** [comment]
Created: 1837415
Reviewed: 1832365

**Comment by Matheusvieria** [comment]
created: 1819882
reviewed: 1816980

**Comment by RuanAmorim** [comment]
Created: 1840946
Reviewed: 1819882

**Comment by sidneipinho** [comment]
create: 1841028
Reviewed: 1837415

**Comment by BrunoSousa95** [comment]
created: 1820731
reviewed: 1819308 (description added, backup procedure and image updated)

**Comment by raquelfoliveira** [comment]
created:1842185
reviewed:1817138 (very useful)

**Comment by jonathanalmeida** [comment]
created:1843309
reviewed:1841225

**Comment by viniciusjanuario** [comment]
Criado: 1843353
Revisado: 1841225

**Comment by derekparanhos** [comment]
Criado: 1843806
Revisado: 1819264

**Comment by jonaswchagas** [comment]
created: 1819308
reviewed: 1843806 (Changing links with prints in images.)

**Comment by LeonardoPeixoto** [comment]
created: 1844545
reviewed: 1843806 (changed link for image)

**Comment by Sabrinanunes** [comment]
created: 1843597
reviewed: 1832375 (Only a few grammatical corrections)

2018-04-27 14:40 GMT-03:00 LeonardoPeixoto <notifications@github.com>:

**Comment by jeiveg** [comment]
Create: 1832375
Review : 1843597

**Comment by ismael35** [comment]
Create: 1844790
Review: 1845042

**Comment by victormmachado** [comment]
Create: 1819412
Review: 1820731

**Comment by luizfurtado0** [comment]
Create: 1852763
Review: 1820198
