### ISSUE TITLE
Train and enable at least 2 agents for answering ReclameAqui, Facebook, Google Business, TrustPilot, etc.

### ISSUE THREAD

**Issue by samuelweblink** [hostinger/brazil#2]
- [x] Designate agents:
@lucasmartins94 
@RuanAmorim 

Briefing and Instructions:
  - [x] @lucasmartins94
  - [x] @RuanAmorim

**Comment by raquelfoliveira** [comment]
@RuanAmorim  OK!

Access - TP/RA Shared.

- [ ] Facebook (H/W)
- [ ] Instagram
- [ ] Twitter
- [ ] Trustpilot
- [ ] Google
- [ ] Business (H/W)
- [ ] Reclame aqui (H/W)
- [ ] Control spreadsheet (H/W)
